package constants;

import java.awt.Color;

public class Constants {

	private static final String MESSAGE_NAME_CITY= "Nombre ciudad ";
	private static final String MESSAGE_ID_HOSPITAL = "Id hospital";
	private static final String MESSAGE_NAME_HOSPITAL = "Nombre hospital";
	private static final String MESSAGE_TYPE_DOCUMENT = "Tipo de documento";
	private static final String MESSAGE_ID_PATIENT = "Numero Documento";
	private static final String FIRST_NAME= "Nombres";
	private static final String LAST_NAME= "Apellidos";
	private static final String MESSAGE_SHOW_LOCAL_DATE = "Fecha de nacimiento";
	private static final String MESSAGE_CORMORBIDITIES = "Comorbilidades";
	private static final String MESSAGE_SHOW_LOCAL_DATE_TAKE_DAY = "Fecha de toma";
	private static final String MESSAGE_PATIENT_IS_VACUNED = "¿Esta vacunado?";
	private static final String MESSAGE_PATIENT_HAD_COVID = "¿Tuvo Covid?";
	public static final Object[] HEADERS = {MESSAGE_NAME_CITY,MESSAGE_ID_HOSPITAL,MESSAGE_NAME_HOSPITAL,MESSAGE_TYPE_DOCUMENT,MESSAGE_ID_PATIENT,FIRST_NAME,LAST_NAME,MESSAGE_SHOW_LOCAL_DATE,MESSAGE_CORMORBIDITIES,MESSAGE_SHOW_LOCAL_DATE_TAKE_DAY,MESSAGE_PATIENT_IS_VACUNED,MESSAGE_PATIENT_HAD_COVID};
	public static final Color BLUE_LIGHT = new Color(106,181,255);
	public static final Color DRAY_lIGHT = new Color(219,219,219);
	public static final Color BLUE_LIGHT_TWO = new Color(189,192,225);
	public static final String MESSAGE_REGISTER = "registrarse";
	public static final String LOGIN_MESSAGE = "ingresar";
	public static final String ACCEPT_PANEL_REGISTER_MESSAGE = "aceptar panel resgistrarse";
	public static final String CANCELED_PANEL_REGISTER_MESSAGE = "cancelar panel registrarse";
	public static final String DATE_FORMAT = "dd-MM-yyyy";
	public static final String GET_MESSAGE_INFORMATION_COVID = "obtener informacion covid";
	public static final String GET_NOTICE_COVID_19 = "obtener noticias covid19";
	public static final String GET_EVENTS_COVID_19 = "obtener eventos covid19";
	public static final String MESSAGE_LOGIN_ADMINISTRATOR = "ingresar panel admnistrador";
	public static final String MESSAGE_CANCELED_ADMINISTRATOR = "cancelar panel admnistrador";
	public static final String MESSAGE_ADD_PANELJTABLE = "Añadir panel jtable";
	public static final String MESSAGE_REMOVE_PANELJTABLE = "eliminar datos del panel jtable";
	public static final String MESSAGE_ADD_PANELJTABLE_PATIENT= "Añadir panel jtable un paciente";
	public static final String MESSAGE_ADD_PANELJTABLE_HEALTHPOST= "Añadir panel jtable un hospital";
	public static final String MESSAGE_ADD_PANELJTABLE_CITY = "Añadir panel jtable una cuidad";
	public static final String MESSAGE_CREATE_CITY = "Crear cuidad";
	public static final String MESSAGE_CREATE_HEALTH_POST = "Crear centro de salud";
	public static final String MESSAGE_ADD_PATIENT = "añadir paciente a un hospital";
	public static final String MESSAGE_CANCELED_CITY = "Borrar datos de ventana emergente de creacion en el panel cuidad";
	public static final String MESSAGE_CANCELED_HEALTH_POST = "Borrar datos de ventana emergente de creacion en el panel hospital";
	public static final String MESSAGE_CANCELED_PATIENT = "Borrar datos de ventana emergente de creacion en el panel paciente";
	public static final String MESSAGE_SHOW_BAR_GRAPHIC = "Observar graficos barras";
	public static final String MESSAGE_SHOW_PIE_CHART = "Observar graficos torta";
	public static final String MESSAGE_GET_OUT_OF_THE_SYSTEM = "Salir del sistema";
	public static final String MESSAGE_SHOW_GRAPICHS_BAR_PATIENT_VACUNED_FOR_CITY = "pacientes vacunados de una cuidad";
	public static final String MESSAGE_SHOW_GRAPICHS_BAR_PATIENT_TEST_TAKE_PER_MONTH = "pruebas tomadas por mes";
	public static final String MESSAGE_SHOW_GRAPICHS_BAR_PATIENT_POSITIVE = "pacientes positivos por edad de un hospital";
	public static final String MESSAGE_SHOW_GRAPICHS_BAR_FOR_DOCUMENT_TYPE = "pacientes positivos por tipo de documento";
	public static final String MESSAGE_RETURN_TO_GRAPHICS_PANEL = "volver al panel de graficas";
	public static final String MESSAGE_SHOW_GRAPICHS_CAKE_PATIENT_VACUNED_FOR_CITY = "pacientes vacunados de una cuidad graficas de pastel";
	public static final String MESSAGE_RETURN_TO_GRAPHICS_PANEL_CAKE = "volver al panel de graficas de pastel";
	public static final String MESSAGE_SHOW_GRAPICHS_CAKE_PATIENT_TEST_TAKE_PER_MONTH = "pruebas tomadas por mes de graficas por mes";
	public static final String MESSAGE_SHOW_GRAPICHS_CAKE_PATIENT_TEST_TAKE_PER_AGE = "pacientes positivos por edad de un hospital graficas de pastel";
	public static final String MESSAGE_SHOW_GRAPICHS_CAKE_PATIENT_FOR_DOCUMENT_TYPE = "pacientes positivos por tipo de documento graficas de pastel";
	public static final String MESSAGE_SHOW_GRAPICHS_CAKE_PATIENT_FOR_CORMOBIDITIES = "pacientes con cormobilidades de una determinada cuidad graficas de pastel";
	public static final String MESSAGE_SHOW_GRAPICHS_BAR_PATIENT_FOR_CORMOBIDITIES = "pacientes con cormobilidades de una determinada cuidad graficas de barras";
	public static final String RETURN_PANEL_INITIAL_VIEW_MOBILE = "volver al panel inicial";
	public static final String MESSAGE_RETURN_PANEL_TABLE = "Volver a ver la tabla";
	public static final String MESSAGE_ENTER_PANEL_REGISTER_ADMINISTRATOR_MOVIL = "ingresar movil ";
	public static final String MESSAGE_SHOW_GRAPHICS_CAKE_FOR_CITY = "Ver grafico por documento por cuidad";
	public static final String MESSAGE_CONFIRMATION_CLOSE = "cerrar aplicacion";
	public static final String MESSAGE_LOGIN_ADMINISTRATOR_ENTER = "login";
	public static final String MESSAGE_UPDATE_CITY = "updateCity";
	public static final String MESSAGE_UPDATE_HEALTHPOST = "updateHealthPost";
	public static final String MESSAGE_UPDATE_PATIENT = "updatePatient";
	public static final String MESSAGE_PORCENTAGE = "getPorcentage";
}
